### ISSUE TITLE
Not working with insets

### ISSUE THREAD

**Issue by a33nazarenko** [Aashu-Dubey/capacitor-statusbar-safe-area#1]
I got the insets, but when I paste this to the scss file, I cant get any result for my page, how is it working? Any help please

**Comment by Aashu-Dubey** [comment]
Hi, How are you accessing the insets in the SCSS file?

To use insets in SCSS you need to call `SafeAreaController.injectCSSVariables()` at the app initialisation as mentioned in the readme [here](https://github.com/Aashu-Dubey/capacitor-statusbar-safe-area#usage), then you can use CSS variables exposed by the package like this

```scss
.myElement {
  padding-top: var(--safe-area-inset-top);
  padding-left: var(--safe-area-inset-left);
  padding-right: var(--safe-area-inset-right);
  padding-bottom: var(--safe-area-inset-bottom);
}
```

Let me know if it still doesn't work.

**Comment by a33nazarenko** [comment]
my SCSS

body {
  margin: 0;
  background-color: #fff!important;
  padding-top: constant(--safe-area-inset-top)!important;
  padding-left: constant(--safe-area-inset-left)!important;
  padding-right: constant(--safe-area-inset-right)!important;
  padding-bottom: constant(--safe-area-inset-bottom)!important;
}

in my app.component file, I initialize your methods
    this.getSafeAreaInsets();
    this.injectSafeAreaVariables();
i cant get any insets with capacitor, my project is capacitor + angular, not ionic, and i have not any solutions for this. Thanks

**Comment by Aashu-Dubey** [comment]
Can you please try `var()` instead of `constant()`?
like this 
```scss
body {
  margin: 0;
  background-color: #fff!important;
  padding-top: var(--safe-area-inset-top)!important;
  padding-left: var(--safe-area-inset-left)!important;
  padding-right: var(--safe-area-inset-right)!important;
  padding-bottom: var(--safe-area-inset-bottom)!important;
}
````

As far as `SafeAreaController.injectCSSVariables()` method is being called, you should be able to access CSS variables.
